- name: configure zeppelin
  template: src={{item}}.j2 dest={{zeppelin_install_dir}}/conf/{{item}} owner={{zeppelin_user}}
  with_items:
     - zeppelin-site.xml
     - zeppelin-env.sh

- name: add jar dependency links
  file: src="{{item.path}}" dest={{zeppelin_install_dir}}/lib/{{item.name}} owner={{zeppelin_user}} state=link
  with_items: zeppelin_jars

